### ISSUE TITLE
delete yourself

### ISSUE THREAD

**Issue by TheVision6212** [ProgramistaZpolski/delete-react#1]
tak jak wyżej

**Comment by chickeeen** [comment]
jesteś niepełnosprawny umysłowo @ProgramistaZpolski

**Comment by ProgramistaZpolski** [comment]
>  delete yourself
why

> jesteś niepełnosprawny umysłowo @ProgramistaZpolski
i don't care

**Comment by kukanq** [comment]
debil lubi php czyli porn hub premium

**Comment by ProgramistaZpolski** [comment]
KUKANQ NA GITHUBIE XDDDDDDDDDDDDDDDDDDd

**Comment by kukanq** [comment]
spierdalaj

**Comment by ProgramistaZpolski** [comment]
Also PHP - Personal Home Page a nie

**Comment by TheVision6212** [comment]
ciekawe jakie filmy ogląda na tym swoim premium

**Comment by chickeeen** [comment]
> KUKANQ NA GITHUBIE XDDDDDDDDDDDDDDDDDDd

masz coś do tego?

**Comment by ProgramistaZpolski** [comment]
> > KUKANQ NA GITHUBIE XDDDDDDDDDDDDDDDDDDd
> 
> masz coś do tego?

Tak, github to miejsce od wrzucania kodu a kukanq nie umie programować

**Comment by chickeeen** [comment]
![image](https://user-images.githubusercontent.com/78041063/110927384-da094000-8325-11eb-81cc-50e1e7dc349b.png)
btw hm yes

**Comment by kukanq** [comment]
^

**Comment by kukanq** [comment]
a moze ja sie chce nauczyc programowac po to chyba kurwa zrobilem githuba zeby programowac

**Comment by chickeeen** [comment]
> Tak, github to miejsce od wrzucania kodu a kukanq nie umie programować

ale będzie się uczył
jak masz problem
tam są drzwi ----------> 🚪

**Comment by kukanq** [comment]
tak

**Comment by kukanq** [comment]
>ciekawe jakie filmy ogląda na tym swoim premium
pewnie gdzie robią nie powiem co

**Comment by ProgramistaZpolski** [comment]
PHP = personal home page...

**Comment by TheVision6212** [comment]
> 
> 
> PHP = personal home page...

PHP = PornHub Premium

**Comment by chickeeen** [comment]
PHP = porn hub premium

**Comment by kukanq** [comment]
[[](url)``]([url]([url]([url](url))))

**Comment by kukanq** [comment]
![Uploading asdasdsaads.PNG…]()

**Comment by ProgramistaZpolski** [comment]
![Screenshot_2021-03-12 ProgramistaZpolski delete-react](https://user-images.githubusercontent.com/37271169/110927683-3bc9aa00-8326-11eb-8ed1-bea6de7634a5.png)
kukanq mistrz markdowna

**Comment by kukanq** [comment]
xd

**Comment by kukanq** [comment]
spadaj

**Comment by kukanq** [comment]
https://cdn.discordapp.com/attachments/723910857729376288/819879914843930674/asdasdsaads.PNG

**Comment by kukanq** [comment]
![image](https://user-images.githubusercontent.com/80518389/110927776-58fe7880-8326-11eb-9988-2c49dac911e5.png)

**Comment by chickeeen** [comment]
![image](https://user-images.githubusercontent.com/78041063/110927765-556af180-8326-11eb-823a-3a17e95b5171.png)

**Comment by ProgramistaZpolski** [comment]
?

**Comment by chickeeen** [comment]
Cooking simulator
to przeciez gra, wiec zlo

gaz
butla z gazem, zlo

gamerhash
pzpl kopie bitcoiny

free online games
( ͡° ͜ʖ ͡°)

**Comment by kukanq** [comment]
kurwa spierdalaj biały motyw jest dobry

**Comment by ProgramistaZpolski** [comment]
> free online games
> ( ͡° ͜ʖ ͡°)

pobierałem https://www.kraisoft.com/puzzle-games/abcisland/online.htm

**Comment by TheVision6212** [comment]
( ͡° ͜ʖ ͡°)

**Comment by kukanq** [comment]
programista przestan ogladac porn hub premium

**Comment by chickeeen** [comment]
idz grac w club penguin

**Comment by ProgramistaZpolski** [comment]
> idz grac w club penguin

ok, no problem

**Comment by kukanq** [comment]
zagraj w minecraft nie masz psychy

**Comment by ProgramistaZpolski** [comment]
> zagraj w minecraft nie masz psychy

nie, club penguin lepszy, in fact mam tam już 3 lata konto

**Comment by kukanq** [comment]
minecraft lepszy mozesz robic co chesz

**Comment by chickeeen** [comment]
chwila mam pomysł, proszę poczekać

**Comment by chickeeen** [comment]
gdy pzpl widzi komentarz "php to zło"
![image](https://user-images.githubusercontent.com/78041063/110928780-8bf53c00-8327-11eb-8a76-45904594b902.png)
