### ISSUE TITLE
Block GraphQL and VulcanJS

### ISSUE THREAD

**Issue by ProgramistaZpolski** [ProgramistaZpolski/delete-react#2]
we need to block that

**Comment by chickeeen** [comment]
mam pomysl!
delete-pzpl

**Comment by chickeeen** [comment]
jaki spam, daje pomysl ci przeciez pedale

**Comment by chickeeen** [comment]
susus amogus
![image](https://user-images.githubusercontent.com/78041063/110929786-a380f480-8328-11eb-9d28-8a4830238357.png)

**Comment by kukanq** [comment]
delete pzpl

**Comment by ProgramistaZpolski** [comment]
update: vulcanjs is blocked
